// Auth actions


// Business actions
export const FETCH_BUSINESSES_REQUEST = "FETCH_BUSINESSES_REQUEST";
export const FETCH_BUSINESSES_SUCCESS = "FETCH_BUSINESSES_SUCCESS";
export const FETCH_BUSINESSES_FAILURE = "FETCH_BUSINESSES_FAILURE";
export const ADD_BUSINESS_REQUEST = "ADD_BUSINESS_REQUEST";
export const ADD_BUSINESS_SUCCESS = "ADD_BUSINESS_SUCCESS";
export const ADD_BUSINESS_FAILURE = "ADD_BUSINESS_FAILURE";

// Courses actions
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";

// Atecos actions
export const FETCH_ATECOS_SUCCESS = "FETCH_ATECOS_SUCCESS";
export const FETCH_ATECOS_FAILURE = "FETCH_ATECOS_FAILURE";

// Types actions
export const FETCH_TYPES_SUCCESS = "FETCH_TYPES_SUCCESS";
export const FETCH_TYPES_FAILURE = "FETCH_TYPES_FAILURE";

// Locations actions
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAILURE = "FETCH_LOCATIONS_FAILURE";

// Business and their addresses actions
export const FETCH_BUSINESSES_ADDRESSES_REQUEST = "FETCH_BUSINESSES_ADDRESSES_REQUEST";
export const FETCH_BUSINESSES_ADDRESSES_SUCCESS = "FETCH_BUSINESSES_ADDRESSES_SUCCESS";
export const FETCH_BUSINESSES_ADDRESSES_FAILURE = "FETCH_BUSINESSES_ADDRESSES_FAILURE";

// Pagination actions
export const FETCH_PAGINATION_REQUEST = "FETCH_PAGINATION_REQUEST";
export const FETCH_PAGINATION_SUCCESS = "FETCH_PAGINATION_SUCCESS";
export const FETCH_PAGINATION_FAILURE = "FETCH_PAGINATION_FAILURE";