// Auth actions


// Business actions
export const FETCH_BUSINESSES_SUCCESS = "FETCH_BUSINESSES_SUCCESS";
export const FETCH_BUSINESSES_STARTED = "FETCH_BUSINESSES_STARTED";
export const FETCH_BUSINESSES_FAILURE = "FETCH_BUSINESSES_FAILURE";